### PR TITLE
fix(extension-version): disable multiplication when noversiontransform

### PR DESCRIPTION
**Pull request by marceloavf**
Allow to disable the multiply of the patch number.

### CODE REVIEW

**Comment by asiffermann** [comment]
Hi @marceloavf and thank you for your PR!

I must say I'm not very happy to introduce a new option, and mostly I think the multiplication of the patch number should be disabled if `options.noversiontransform` is true.

I'd love to have @sandorfr thoughts on this, as it was him who introduced the `noversiontransform` option first...

**Comment by marceloavf** [comment]
Hi @asiffermann, thank you for your response!

I was thinking of disabling multiplication of the patch with `options.noversiontransform` too, but I don't know the implications of this change, so I proposed this new option.

**Comment by marceloavf** [comment]
Redone it as the way we talked.

**Review by asiffermann — APPROVED** [review]

**Comment by asiffermann** [comment]
Great! Many thanks! 😃

**Pull request merged**
